#!/bin/sh

usage() {
	echo "Usage: $(basename $0) <tarball-uri> <prefix> [<flags>][...] [-- <bootstrap>]" >&2
	exit 1
}
[ -n "$1" ] && [ -n "$2" ] || usage

TARBALL=$1
if echo $TARBALL | egrep \\.bz2; then
	TARFLAG=j
else
	TARFLAG=z
fi
PREFIX=$2
FLAGS=$(echo "$* " | cut -d " " -f 3- | sed "s/-- .*//")
if echo $* | grep " -- " >/dev/null; then
	BOOTSTRAP=$(echo "$*" | cut -d ' ' -f 3- | sed "s/.* -- //")
fi

[ -f "$PREFIX/.sourceinstall" ] && exit 0

mkdir /tmp/sourceinstall-$$
cd /tmp/sourceinstall-$$
wget -O - $TARBALL | tar x$TARFLAG
cd *
[ -n "$BOOTSTRAP" ] && eval "$BOOTSTRAP"
./configure $FLAGS --prefix=$PREFIX
make
make install
cd /tmp
rm -rf /tmp/sourceinstall-$$

touch $PREFIX/.sourceinstall
